// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
import { existsSync } from "fs";
import path from "path";
import { defineConfig } from "@prisma/config";

// Ensure DATABASE_URL is available. If not set in the current working
// directory, attempt to load the workspace root .env (one level up).
if (!process.env.DATABASE_URL) {
  const localEnv = path.resolve(process.cwd(), ".env");
  const parentEnv = path.resolve(__dirname, "..", ".env");

  if (existsSync(localEnv)) {
    dotenvConfig({ path: localEnv });
  } else if (existsSync(parentEnv)) {
    dotenvConfig({ path: parentEnv });
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});
